### PR TITLE
cli: completion: Add support for Nushell completions

### LINKED ISSUE #2323: FR: nushell completion support
**Is your feature request related to a problem? Please describe.**
Clap is used by jujutsu already, so nushell intergration/support should be pretty easy to do in theory.

**Describe the solution you'd like**
Clap should generate the completion for nushell, making jujutsu support shell completion.

### PR DESCRIPTION
**Pull request by poliorcetics**
Incidentally, I also fixed outdated docs in the command help for other shells (still using `--<shell>` instead of the positional form)

# Checklist

If applicable:
- [x] I have updated `CHANGELOG.md`
- [x] I have updated the documentation (README.md, docs/, demos/) (command documentation)
- [ ] I have updated the config schema (cli/src/config-schema.json)
- [x] I have added tests to cover my changes

# Dependencies

- Needs https://github.com/clap-rs/clap/pull/5359 to work
- Needs #3074

- Closes #2353
- Closes #2323

### CODE REVIEW

**Review by PhilipMetzger — APPROVED** [review]
LGTM, could you please adhere to our commit style too, like `cli:` and `lib:`?

**Comment by PhilipMetzger** [comment]
And it seems you forgot to update the snapshot of the cli-reference.

**Comment by poliorcetics** [comment]
@PhilipMetzger done to both !

**Comment by thoughtpolice** [comment]
Note that in #2353 this was also attempted, but due to a bug in `clap_complete_nushell` it actually generates invalid nushell code. I assume your [upstream commit](https://github.com/clap-rs/clap/commit/e782775229081697e47d340a155d6b087eeb46f8) fixes this behavior?

**Comment by poliorcetics** [comment]
> I assume your upstream commit fixes this behavior

Yes, and it's been released with 4.5.1, so this PR is now ready. Thanks for pointing out the existing issues and PRs :)

**Comment by PhilipMetzger** [comment]
Can you add a Closes #2323 to the commit message or the PR description? Then it should be good to land.

**Comment by poliorcetics** [comment]
Yes done

**Review by thoughtpolice — APPROVED** [review]
lgtm 👍🏻

**Comment by poliorcetics** [comment]
Rebased on top of https://github.com/martinvonz/jj/pull/3062 so I can finally merge them sequentially without them interfering with each other in the changelog

**Review by lucasfcnunes — COMMENTED** [review]
Too late, but... (But I made a [comment](https://github.com/jj-vcs/jj/commit/c75230747af0f3182b013155913b9809701e078a#r183055858) about `powershell` -> `power-shell` being a mistake)

**Pull request merged**
