### PR TITLE
README: replace outdated claim about lacking git blame support

### PR DESCRIPTION
**Pull request by keanemind**
Addresses https://github.com/jj-vcs/jj/issues/5191

# Checklist

If applicable:
- [ ] I have updated `CHANGELOG.md`
- [x] I have updated the documentation (README.md, docs/, demos/)
- [ ] I have updated the config schema (cli/src/config-schema.json)
- [ ] I have added tests to cover my changes

### CODE REVIEW

**Comment by arxanas** [comment]
^ re CLA see https://github.com/jj-vcs/jj/discussions/4849

**Comment by keanemind** [comment]
Whoops, just signed it. Any thoughts on the new wording I used?

**Comment by keanemind** [comment]
Oh something looks off about the commit, I think my auto formatter for Markdown kicked in

**Review by arxanas — APPROVED** [review]
Seems fine to me, thanks!

**Pull request merged**
